use strict;
use warnings;




my $mRNA = <<"_END_";
AUGCACCGGCCCCCCCGAGCAGGCGCGAAGACGUGAAUGGGGAAAAACAAACCGCAGGGCGCGGAGA
ACAGACCACCGGCCCGCGGACGCGAAAAGCAAAGGGAAAAGACGGGAUAAAUGGAGGGACCCGAAGC
AGCAGCGGAGGACGCCCCCAAGAAGCAAACGAAAUGAAUGGGCAGAAGCACAGACAGAACCACCCAG
UAGAUGAAGCGGGAGAAGAAGGCGCCAGGCCGGGACCAAGAAGAACCAACCAACAGCCCGACGUAGA
UGGGAGCGCCGCGCAAGCACCAAGGGCACAAGCGGGCCGCCCGACGCCGAGGGCCACCCCAGGAGCA
CGGACGCAGAGCAAGAUAAAUGAAAAAGGCGAAGGGACCGAGCACGUAGAUGACGGCCCAACCGGAG
CGAGACCAACACAAGGGGGGGGAGCCAAGGAAAAGGGCGAGCCCAGGGUGA
_END_


$mRNA =~ s/[^AUCG]//g;


my (@ORF,$run,$length);

for(my $i=0; $i<length($mRNA); $i++){

	@ORF=();
	if(substr($mRNA,$i,3) eq "AUG"){
		
		$run=substr($mRNA,$i);
		
		for(my $k=0; $k < length($run); $k=$k+3){
			push(@ORF,substr($run, $k,3));
		}

		
		for(my $k=0;$k<scalar(@ORF); $k++){
			if($ORF[$k] eq "UAA" || $ORF[$k] eq "UAG" || $ORF[$k] eq "UGA"){
				

				$length = $k*3+3;
				print @ORF[0..$k]," ($length)\n";
				last;
			}
		}
	}
}